db:
    image: mongo:3.6.0
    volumes:
      - /data/db
    ports:
      - '27017:27017'
    command: --smallfiles

web:
    build: .
    command: npm run serve
    environment:
      NODE_ENV: 'docker-development'
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    links:
      - db:dockerized_mongo
