export const GLOBAL_HIDEMSG = 'GLOBAL_HIDEMSG'
export const GLOBAL_LOADDING = 'GLOBAL_LOADDING'
export const GLOBAL_PROGRESS = 'GLOBAL_PROGRESS'
export const GLOBAL_SHOWMSG = 'GLOBAL_SHOWMSG'
export const GLOBAL_LOGIN_FORM = 'GLOBAL_LOGIN_FORM'
export const GLOBAL_LOGIN_STATUS = 'GLOBAL_LOGIN_STATUS'

export const TOPICS_LIST = 'TOPICS_LIST'
export const TOPICS_ARTICLE = 'TOPICS_ARTICLE'
export const TOPICS_COMMENT = 'TOPICS_COMMENT'
export const TOPICS_COMMENT_INSERT = 'TOPICS_COMMENT_INSERT'

export const RECEIVE_ADMIN_TOPICS = 'RECEIVE_ADMIN_TOPICS'
export const RECEIVE_ADMIN_ARTICLE = 'RECEIVE_ADMIN_ARTICLE'

export const UPDATE_ADMIN_ARTICLE = 'UPDATE_ADMIN_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const RECOVER_ARTICLE = 'RECOVER_ARTICLE'
