export const TOPICS_LIST = 'TOPICS_LIST'
export const TOPICS_ARTICLE = 'TOPICS_ARTICLE'
export const TOPICS_COMMENT = 'TOPICS_COMMENT'

export const RECEIVE_ADMIN_TOPICS = 'RECEIVE_ADMIN_TOPICS'
export const RECEIVE_ADMIN_ARTICLE = 'RECEIVE_ADMIN_ARTICLE'

export const UPDATE_ADMIN_ARTICLE = 'UPDATE_ADMIN_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const RECOVER_ARTICLE = 'RECOVER_ARTICLE'
